# TCL File Generated by Component Editor 18.1
# Tue Jul 16 14:02:38 CEST 2024
# DO NOT MODIFY


# 
# charge_injection_pulser "Charge Injection Pulser" v4.0.5
# Yifeng Wang 2024.07.16.14:02:38
# Generate arbitary pulse for a set width and frequency
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module charge_injection_pulser
# 
set_module_property DESCRIPTION "Generate arbitary pulse for a set width and frequency"
set_module_property NAME charge_injection_pulser
set_module_property VERSION 4.0.5
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Mu3e Control Plane/Modules"
set_module_property AUTHOR "Yifeng Wang"
set_module_property ICON_PATH ../drawings/20121123203030!Logo_drawing100.png
set_module_property DISPLAY_NAME "Charge Injection Pulser"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL charge_inj_pulser
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file charge_inj_pulser.vhd VHDL PATH charge_inj_pulser.vhd TOP_LEVEL_FILE
add_fileset_file alt_lpm_div.vhd VHDL PATH lpm_div/alt_lpm_div.vhd


# 
# parameters
# 
add_parameter DEF_PULSE_FREQ NATURAL 100000
set_parameter_property DEF_PULSE_FREQ DEFAULT_VALUE 100000
set_parameter_property DEF_PULSE_FREQ DISPLAY_NAME DEF_PULSE_FREQ
set_parameter_property DEF_PULSE_FREQ TYPE NATURAL
set_parameter_property DEF_PULSE_FREQ UNITS None
set_parameter_property DEF_PULSE_FREQ ALLOWED_RANGES 0:2147483647
set_parameter_property DEF_PULSE_FREQ HDL_PARAMETER true
add_parameter DEF_PULSE_WIDTH NATURAL 2
set_parameter_property DEF_PULSE_WIDTH DEFAULT_VALUE 2
set_parameter_property DEF_PULSE_WIDTH DISPLAY_NAME DEF_PULSE_WIDTH
set_parameter_property DEF_PULSE_WIDTH TYPE NATURAL
set_parameter_property DEF_PULSE_WIDTH UNITS None
set_parameter_property DEF_PULSE_WIDTH ALLOWED_RANGES 0:2147483647
set_parameter_property DEF_PULSE_WIDTH HDL_PARAMETER true
add_parameter CLK_FREQUENCY NATURAL 125000000
set_parameter_property CLK_FREQUENCY DEFAULT_VALUE 125000000
set_parameter_property CLK_FREQUENCY DISPLAY_NAME CLK_FREQUENCY
set_parameter_property CLK_FREQUENCY TYPE NATURAL
set_parameter_property CLK_FREQUENCY UNITS None
set_parameter_property CLK_FREQUENCY ALLOWED_RANGES 0:2147483647
set_parameter_property CLK_FREQUENCY HDL_PARAMETER true
add_parameter DEBUG NATURAL 1
set_parameter_property DEBUG DEFAULT_VALUE 1
set_parameter_property DEBUG DISPLAY_NAME DEBUG
set_parameter_property DEBUG TYPE NATURAL
set_parameter_property DEBUG ENABLED false
set_parameter_property DEBUG UNITS None
set_parameter_property DEBUG ALLOWED_RANGES 0:2147483647
set_parameter_property DEBUG HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock_interface
# 
add_interface clock_interface clock end
set_interface_property clock_interface clockRate 125000000
set_interface_property clock_interface ENABLED true
set_interface_property clock_interface EXPORT_OF ""
set_interface_property clock_interface PORT_NAME_MAP ""
set_interface_property clock_interface CMSIS_SVD_VARIABLES ""
set_interface_property clock_interface SVD_ADDRESS_GROUP ""

add_interface_port clock_interface i_clk clk Input 1


# 
# connection point csr_avmm
# 
add_interface csr_avmm avalon end
set_interface_property csr_avmm addressUnits WORDS
set_interface_property csr_avmm associatedClock clock_interface
set_interface_property csr_avmm associatedReset reset_interface
set_interface_property csr_avmm bitsPerSymbol 8
set_interface_property csr_avmm burstOnBurstBoundariesOnly false
set_interface_property csr_avmm burstcountUnits WORDS
set_interface_property csr_avmm explicitAddressSpan 0
set_interface_property csr_avmm holdTime 0
set_interface_property csr_avmm linewrapBursts false
set_interface_property csr_avmm maximumPendingReadTransactions 0
set_interface_property csr_avmm maximumPendingWriteTransactions 0
set_interface_property csr_avmm readLatency 0
set_interface_property csr_avmm readWaitTime 1
set_interface_property csr_avmm setupTime 0
set_interface_property csr_avmm timingUnits Cycles
set_interface_property csr_avmm writeWaitTime 0
set_interface_property csr_avmm ENABLED true
set_interface_property csr_avmm EXPORT_OF ""
set_interface_property csr_avmm PORT_NAME_MAP ""
set_interface_property csr_avmm CMSIS_SVD_VARIABLES ""
set_interface_property csr_avmm SVD_ADDRESS_GROUP ""

add_interface_port csr_avmm avs_csr_writedata writedata Input 32
add_interface_port csr_avmm avs_csr_write write Input 1
add_interface_port csr_avmm avs_csr_waitrequest waitrequest Output 1
set_interface_assignment csr_avmm embeddedsw.configuration.isFlash 0
set_interface_assignment csr_avmm embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment csr_avmm embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment csr_avmm embeddedsw.configuration.isPrintableDevice 0


# 
# connection point pulse_out_conduit
# 
add_interface pulse_out_conduit conduit end
set_interface_property pulse_out_conduit associatedClock ""
set_interface_property pulse_out_conduit associatedReset ""
set_interface_property pulse_out_conduit ENABLED true
set_interface_property pulse_out_conduit EXPORT_OF ""
set_interface_property pulse_out_conduit PORT_NAME_MAP ""
set_interface_property pulse_out_conduit CMSIS_SVD_VARIABLES ""
set_interface_property pulse_out_conduit SVD_ADDRESS_GROUP ""

add_interface_port pulse_out_conduit o_pulse std_logic Output 1


# 
# connection point reset_interface
# 
add_interface reset_interface reset end
set_interface_property reset_interface associatedClock clock_interface
set_interface_property reset_interface synchronousEdges DEASSERT
set_interface_property reset_interface ENABLED true
set_interface_property reset_interface EXPORT_OF ""
set_interface_property reset_interface PORT_NAME_MAP ""
set_interface_property reset_interface CMSIS_SVD_VARIABLES ""
set_interface_property reset_interface SVD_ADDRESS_GROUP ""

add_interface_port reset_interface i_rst reset Input 1

